version: "2"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    command: npm run dev
